# Dockerfile pour le développement

FROM node:20-alpine

WORKDIR /app

# Installer Angular CLI globalement
RUN npm install -g @angular/cli

# Copier les fichiers de dépendances
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le code source
COPY . .

# Exposer le port de développement
EXPOSE 4200

# Démarrer le serveur de développement
CMD ["ng", "serve", "--host", "0.0.0.0", "--poll", "2000"]
